// 参考：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/throw
// 备注：无

// try...catch语句将能引发错误的代码放在try块中，并且对应一个响应，然后有异常被抛出
// try语句包含了由一个或者多个语句组成的try块, 和至少一个catch子句或者一个finally子句的其中一个，或者两个兼有， 下面是三种形式的try声明：
// try...catch
// try...finally
// try...catch...finally